In [64]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

In [22]:
from keras.datasets import fashion_mnist
(x_train, y_train), (x_test, y_test)=fashion_mnist.load_data()

In [23]:
x_train = x_train.astype("float32") / 255
x_test = x_test.astype("float32") / 255
x_train = np.expand_dims(x_train, -1)
x_test = np.expand_dims(x_test, -1)

y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

In [25]:
x_train.shape

(60000, 28, 28, 1)

In [123]:
model = keras.Sequential(
    [
        keras.Input(shape=(28, 28, 1)),
        keras.layers.Conv2D(8, padding='same',kernel_size=(3, 3), activation="relu"),
        #keras.layers.MaxPooling2D(pool_size=(2, 2)),
        keras.layers.Conv2D(16, padding='same',kernel_size=(3, 3), activation="relu"),
        #keras.layers.MaxPooling2D(pool_size=(2, 2)),
        keras.layers.Conv2D(32, padding='same',kernel_size=(3, 3), activation="relu"),
        keras.layers.MaxPooling2D(pool_size=(2, 2)),
        keras.layers.Conv2D(64, padding='same',kernel_size=(3, 3), activation="relu"),
        keras.layers.MaxPooling2D(pool_size=(2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dropout(0.5),
        keras.layers.Dense(10, activation="softmax"),
    ]
)

In [124]:
batch_size = 256
epochs = 15
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)

Epoch 1/15
211/211 [==============================] - 30s 141ms/step - loss: 0.7204 - accuracy: 0.7440 - val_loss: 0.4236 - val_accuracy: 0.8455
Epoch 2/15
211/211 [==============================] - 30s 140ms/step - loss: 0.4180 - accuracy: 0.8486 - val_loss: 0.3486 - val_accuracy: 0.8742
Epoch 3/15
211/211 [==============================] - 29s 138ms/step - loss: 0.3563 - accuracy: 0.8721 - val_loss: 0.3082 - val_accuracy: 0.8855
Epoch 4/15
211/211 [==============================] - 29s 138ms/step - loss: 0.3191 - accuracy: 0.8857 - val_loss: 0.2850 - val_accuracy: 0.8973
Epoch 5/15
211/211 [==============================] - 29s 139ms/step - loss: 0.2962 - accuracy: 0.8939 - val_loss: 0.2706 - val_accuracy: 0.9005
Epoch 6/15
211/211 [==============================] - 29s 138ms/step - loss: 0.2736 - accuracy: 0.9021 - val_loss: 0.2575 - val_accuracy: 0.9070
Epoch 7/15
211/211 [==============================] - 29s 138ms/step - loss: 0.2621 - accuracy: 0.9057 - val_loss: 0.2486 - val_ac

In [125]:
score = model.evaluate(x_test, y_test, verbose=0)
print("Test accuracy: %.4f" %(score[1]*100))


Test accuracy: 92.0600


In [126]:
y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true_classes = np.argmax(y_test, axis=1)

313/313 [==============================] - 1s 4ms/step


In [127]:
confusion_mtx = confusion_matrix(y_true_classes,y_pred_classes)
print(confusion_mtx)

[[887   1  23  20   3   0  62   0   4   0]
 [  2 981   0  14   1   0   2   0   0   0]
 [ 14   1 897  10  36   0  41   0   1   0]
 [ 10   3   8 935  22   0  22   0   0   0]
 [  1   0  32  24 905   0  38   0   0   0]
 [  0   0   0   0   0 980   0  15   0   5]
 [118   1  51  32  95   0 698   0   5   0]
 [  0   0   0   0   0   5   0 982   0  13]
 [  1   1   3   4   2   2   1   3 983   0]
 [  0   0   0   0   0   6   1  35   0 958]]
